# Generate ARFIMA model and its subclasses models

In [1]:
from scientisttseries.arfirma import arfima_simulate

In [2]:
T,sigma = 100000, 0.5

## 

## ARFIMA(0,0.4,0)

In [3]:
import numpy as np
np.random.seed(123)
X = arfima_simulate([], 0.4, [],T, warmup=2**16)
X

array([ 1.11341942,  0.67726991, -0.24281642, ..., -0.52014702,
        1.11529551, -0.2923413 ])

## ARFIM(2,0.15,1)

In [4]:
np.random.seed(123)
X = arfima_simulate([0.3, 0.2], 0.15, [0.5],T, warmup=2**16)
X

array([ 0.73489194, -0.15804165,  0.62605367, ..., -1.66394592,
       -2.21150092, -2.22191023])

## ARIMA(2,1,1  )

In [5]:
np.random.seed(123)
X = arfima_simulate([0.3, 0.2],1, [0.5],T, warmup=2**16)
X

array([ 713.56886531,  713.1801294 ,  713.67722243, ..., 1158.95522018,
       1156.85441001, 1154.86395739])

## 